export const item = {
  0: {
    page: 0,
    que: 'who',
    title: '누구와 떠나고 싶으신가요?',
    list: [
      ['2030', '2030끼리'],
      ['4050', '4050끼리'],
      ['6070', '6070끼리'],
      ['female', '여자끼리'],
      ['male', '남자끼리'],
      ['family', '자녀동반'],
      ['anyone', '누구든지'],
    ],
    overlap: true,
  },
  1: {
    page: 1,
    que: 'where',
    title: '어디로 떠나고 싶으신가요?',
    list: [
      ['sea', '동남아시아'],
      ['nea', '동북-중앙아시아'],
      ['pacific', '서남아시아-태평양'],
      ['eu', '유럽-코카서스'],
      ['america', '북미-중남미'],
      ['africa', '아프리카-중동'],
      ['anyone', '상관없음'],
    ],
    overlap: true,
  },

  2: {
    page: 2,
    que: 'theme',
    title: '어떤 테마의 여행을 가고 싶으신가요?',
    list: [
      ['culture', '문화탐방'],
      ['rest', '휴양지'],
      ['golf', '골프여행'],
      ['trek', '트래킹'],
      ['circuit', '성지순례'],
      ['anyone', '상관없음'],
    ],
    overlap: true,
  },

  3: {
    page: 3,
    que: 'politics',
    title: '정치 성향이 어떻게 되시나요?',
    list: [
      ['conservative', '보수적인 편'],
      ['progressive', '진보적인 편'],
      ['centrist', '중도적'],
      ['anyone', '없음'],
    ],
    overlap: false,
  },

  4: {
    page: 4,
    que: 'religion',
    title: '어떤 종교를 가지고 계신가요?',
    list: [
      ['christian', '기독교'],
      ['catholic', '천주교'],
      ['buddhism', '불교'],
      ['other', '그 외 종교'],
      ['anyone', '무교'],
    ],
    overlap: false,
  },
  5: {
    page: 5,
    que: 'style',
    title: '선호하는 여행 스타일은 무엇인가요?',
    list: [
      ['full', '풀패키지'],
      ['semi', '세미 패키지'],
      ['bag', '배낭 패키지'],
      ['anyone', '상관없음'],
    ],
    addinfo: {
      title: '용어 설명',
      contents: [
        ['풀패키지', '모든 여행일정이 계획되어 있는 패키지를 말합니다.'],
        ['세미 패키지', '계획된 일정과 자유일정이 섞인 패키지를 말합니다'],
        ['배낭 패키지', '모든 일정이 자유일정인 패키지를 말합니다.'],
      ],
    },
  },
  6: {
    page: 6,
    que: 'style',
    title: '여행 기간은 어떻게 계획하고 계신가요?',
    list: [
      ['5', '5일 이하'],
      ['7', '6~7일'],
      ['9', '8~9일'],
      ['15', '10~15일'],
      ['16', '16일 이상'],
      ['anyone', '상관없음'],
    ],
    overlap: true,
  },
  7: {
    page: 7,
    que: 'month',
    title: '어느 달에 여행을 떠나실 계획인가요?',
    list: [
      ['1-3', '1-3월'],
      ['4-6', '4-6월'],
      ['7-9', '7-9월'],
      ['10-12', '10-12월'],
      ['anyone', '상관없음'],
    ],
    overlap: true,
  },
};
